image: us.gcr.io/tools-203611/gitlab-base:24

services:
  - postgres

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

stages:
  - version
  - test
  - sentry
  - 📦 docker
  - helm
  - flake

version:
  stage: version
  script:
    - echo "export VERSION=$(git describe --tags --abbrev=0)" > $CI_PROJECT_DIR/variables
  artifacts:
    paths:
    - variables

tox:
  stage: test
  script:
    - export PATH="/root/.pyenv/bin:$PATH"
    - pyenv local 3.7.1
    - tox

sentry:
  stage: sentry
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/ubiquitypress/kubernetes kubernetes
    - echo "export RELEASE=$(python3 kubernetes/ci/produce_sentry_version_file.py)" > $CI_PROJECT_DIR/release
  artifacts:
    paths:
    - release
    - kubernetes/
  only:
    - tags

build-push-clean:
  stage: 📦 docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - source $CI_PROJECT_DIR/release
    - source $CI_PROJECT_DIR/variables
  script:
    - /kaniko/executor
      --build-arg RELEASE
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --destination "eu.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$VERSION"
  only:
    - tags

helm:
  stage: helm
  script:
    - source $CI_PROJECT_DIR/variables
    - helm init --client-only --skip-refresh
    - helm plugin install https://github.com/hypnoglow/helm-s3.git
    - helm repo add ubiquity s3://service-helm/charts
    - export CHART_VERSION=$(python3 kubernetes/ci/auto_update_chart.py $HELM_PROJECT_NAME $HELM_PROJECT_NAME $IMAGE_NAME)
    - helm package kubernetes/$HELM_PROJECT_NAME/helm/$HELM_PROJECT_NAME
    - helm s3 push --force /builds/ubiquitypress/$IMAGE_NAME/$HELM_PROJECT_NAME-$CHART_VERSION.tgz ubiquity
    - cd kubernetes/
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git commit -am 'auto update helm chart'
    - git push https://${GITLAB_USER_NAME}:${GITLAB_ACCESS_TOKEN}@gitlab.com/ubiquitypress/kubernetes.git HEAD:master
  only:
    - tags

flake:
  stage: flake
  script:
    - flake8 src
  allow_failure: true
