# Generated by Django 2.0.1 on 2018-06-14 16:34

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, help_text='Useful for aggregation.')),
                ('external_id', models.UUIDField(help_text='UUID of the event from the original provider.', unique=True)),
                ('origin_id', models.CharField(help_text='ID of the event in the source, where it originated.', max_length=250)),
                ('created_at', models.DateTimeField(help_text='Time of creation in the service where it originated.')),
                ('content', models.TextField(help_text="Event's content in the service where it originated.")),
                ('uri', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_url', models.URLField()),
                ('allowed_origins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
            ],
        ),
        migrations.CreateModel(
            name='NamespaceUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Namespace')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='DOI not valid.', regex='/^10.\\d{4,9}/[-._;()/:A-Z0-9]+$/i')])),
                ('last_checked', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UriUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importer.CSVUpload')),
                ('uri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Uri')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Uri')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Namespace'),
        ),
        migrations.AddField(
            model_name='measure',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Source'),
        ),
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Measure'),
        ),
        migrations.AddField(
            model_name='event',
            name='scrape',
            field=models.ForeignKey(help_text='Scrape process which pulled the event.', on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Scrape'),
        ),
        migrations.AddField(
            model_name='event',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
