# Generated by Django 2.0.1 on 2018-01-12 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='DOI not valid.', regex='^10.\\d{4,9}/[-._;()/:A-Z0-9]+$')])),
                ('last_checked', models.DateTimeField(default=None, null=True)),
                ('last_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.CSVUpload')),
            ],
        ),
    ]
