# Generated by Django 2.0.1 on 2018-01-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(help_text='UUID of the event from the original provider.', unique=True)),
                ('source_id', models.CharField(help_text='ID of the event in the source, where it originated.', max_length=250)),
                ('source', models.CharField(help_text='Short text indicating the social media source of the event.', max_length=250)),
                ('created_at', models.DateTimeField(help_text='Time of creation in the social media where it originated.')),
                ('content', models.TextField(help_text="Event's content in the social media where it originated.")),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Doi')),
            ],
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Doi')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='scrape',
            field=models.ForeignKey(help_text='Scrape process which pulled the event.', on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Scrape'),
        ),
    ]
