# Generated by Django 2.0.1 on 2018-06-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='doi',
            new_name='uri',
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='processor.Country'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='definition_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uri',
            name='raw',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
