# Generated by Django 2.0.1 on 2018-02-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
        ('processor', '0002_auto_20180129_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoiUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='doi',
            name='last_upload',
        ),
        migrations.AlterField(
            model_name='url',
            name='doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Doi'),
        ),
        migrations.AddField(
            model_name='doiupload',
            name='doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processor.Doi'),
        ),
        migrations.AddField(
            model_name='doiupload',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importer.CSVUpload'),
        ),
    ]
