# Generated by Django 2.0.1 on 2018-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_uri_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(help_text="Event's content in the service where it originated.", null=True),
        ),
    ]
