# Generated by Django 2.0.1 on 2018-04-19 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20180213_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='doi',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='DOI not valid.', regex='/^10.\\d{4,9}/[-._;()/:A-Z0-9]+$/i')]),
        ),
    ]
