"""empty message

Revision ID: 087de1ba87ca
Revises: 
Create Date: 2019-01-03 16:54:07.483677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '087de1ba87ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.String(length=50), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw')
    )
    op.create_table('deleted_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('origin', postgresql.ENUM('twitter', 'citation', 'wikipedia', 'hypothesis', 'facebook', 'wordpressdotcom', name='origins'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri_id', 'subject_id')
    )
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=False),
    sa.Column('origin', postgresql.ENUM('twitter', 'citation', 'wikipedia', 'hypothesis', 'facebook', 'wordpressdotcom', name='origins'), nullable=False),
    sa.Column('provider', postgresql.ENUM('crossref_cited_by', 'crossref_event_data', 'facebook', 'twitter', name='staticproviders'), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('last_successful_scrape_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('origin', postgresql.ENUM('twitter', 'citation', 'wikipedia', 'hypothesis', 'facebook', 'wordpressdotcom', name='origins'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri_id', 'subject_id')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.HSTORE(text_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('origin', postgresql.ENUM('twitter', 'citation', 'wikipedia', 'hypothesis', 'facebook', 'wordpressdotcom', name='origins'), nullable=False),
    sa.Column('provider', postgresql.ENUM('crossref_cited_by', 'crossref_event_data', 'facebook', 'twitter', name='staticproviders'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_event')
    op.drop_table('url')
    op.drop_table('metric')
    op.drop_table('event')
    op.drop_table('error')
    op.drop_table('deleted_event')
    op.drop_table('uri')
    op.drop_table('scrape')
    # ### end Alembic commands ###
