"""empty message

Revision ID: 385d83d68b71
Revises: 5a3a877698c8
Create Date: 2021-01-08 17:09:07.858288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385d83d68b71'
down_revision = '5a3a877698c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uri_prefix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.add_column('error', sa.Column('uri_prefix_id', sa.Integer(), nullable=True))
    op.alter_column('error', 'origin',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('error', 'uri_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('error_uri_prefix_id_fkey', 'error', 'uri_prefix', ['uri_prefix_id'], ['id'])
    op.add_column('uri', sa.Column('prefix', sa.String(), nullable=True))
    op.create_foreign_key('uri_prefix_fkey', 'uri', 'uri_prefix', ['prefix'], ['value'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uri_prefix_fkey', 'uri', type_='foreignkey')
    op.drop_column('uri', 'prefix')
    op.drop_constraint('error_uri_prefix_id_fkey', 'error', type_='foreignkey')
    op.alter_column('error', 'uri_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('error', 'origin',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('error', 'uri_prefix_id')
    op.drop_table('uri_prefix')
    # ### end Alembic commands ###
