"""empty message

Revision ID: 5a3a877698c8
Revises: 8dd046e47a1b
Create Date: 2019-04-23 17:58:41.329045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3a877698c8'
down_revision = '8dd046e47a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'last_updated')
    # ### end Alembic commands ###
