"""empty message

Revision ID: 71b67603ba58
Revises: 3d2acabdde47
Create Date: 2019-02-11 14:03:58.229561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b67603ba58'
down_revision = '3d2acabdde47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('institution', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'institution')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'approved')
    # ### end Alembic commands ###
