"""empty message

Revision ID: 8dd046e47a1b
Revises: 8b5f58e10869
Create Date: 2019-02-18 15:25:46.976117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd046e47a1b'
down_revision = '8b5f58e10869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_event', 'scrape_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_event', 'scrape_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
