"""empty message

Revision ID: bee3e6675afa
Revises: 087de1ba87ca
Create Date: 2019-01-21 19:05:09.134459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee3e6675afa'
down_revision = '087de1ba87ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('uris_users',
    sa.Column('uri_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uri_id'], ['uri.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uri_id', 'user_id')
    )
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'password')
    op.drop_column('user', 'last_updated')
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'active')
    op.drop_table('uris_users')
    op.drop_table('roles_users')
    op.drop_table('role')
    # ### end Alembic commands ###
